services:
  db_postgres:
    container_name: product_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    # networks:
    #   - net

volumes:
  db_data: {}